# config.yaml

number_of_chunks: 5
k: 2
max_number_of_eq_classes: 62500
suppression_limit: 0.01

chunk_directory: small_data
output_path: generalized_chunk1.csv
log_file: log.txt
save_output: true

quasi_identifiers:
  numerical:
    - column: Age
      encode: false
      type: int
    - column: BMI
      encode: true
      type: float
    - column: PIN Code
      encode: true
      type: int
  categorical: 
    - column : Blood Group


bin_width_multiplication_factor:
  Age: 2
  BMI: 2
  PIN Code: 2

hardcoded_min_max:
  Age: [19, 85]
  BMI: [15.2, 32.6]
  PIN Code : [560001, 591346]
